id: ID727A77D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T15:50:14+00:00'
last_modified: '2022-06-07T16:46:26.254056+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18400
  title: མཁའ་འགྲོ་རྒྱ་མཚོའི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4682':
      image_group_id: I8LS18423
      title: ''
      total_pages: 562
      order: 1
      base_file: 4682.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
