id: P002984
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:32:34.621664
source_metadata:
  id: bdr:W8LS18400
  title: མཁའ་འགྲོ་རྒྱ་མཚོའི་རྣམ་ཐར།
  author: ''
  volumes:
    19b7e330743d483bb60e045685fc14ee:
      image_group_id: I8LS18423
      title: ''
      volume_number: 1
      total_pages: 562
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
